image: repo.dev.terastrm.net:5000/ci-cisco-nso:4.2.3

stages:
  - build

build:
  stage: build
  tags:
    - docker-metal
  only:
    - master@TeraStream/ddos-gen
  script:
    - export DOCKER_REGISTRY=gitlab.dev.terastrm.net:4567/terastream
    - make docker-image
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} $CI_REGISTRY
    - make docker-push
